from pathlib import Path

source_path = Path('noethys/Dlg/DLG_Badgeage_interface.py')
source = source_path.read_text(encoding='utf-8')
old = '''                # Recherche les réponses\n                if dictQuestions[IDquestion]["type"] == "individu" :\n                    req = """SELECT IDreponse, reponse\n                    FROM questionnaire_reponses\n                    WHERE IDquestion=%d AND IDindividu=%d;""" % (IDquestion, IDindividu)\n                    DB.ExecuterReq(req)\n                    listeReponses = DB.ResultatReq()     \n\n##                if dictQuestions[IDquestion]["type"] == "famille" :\n'''
new = '''                # Recherche les réponses\n                # Le badgeage ne sait évaluer ici que les questions individuelles.\n                # Une question absente ou d'un autre type doit faire échouer la\n                # condition, et non provoquer un UnboundLocalError plus bas.\n                if IDquestion not in dictQuestions or dictQuestions[IDquestion]["type"] != "individu" :\n                    DB.Close()\n                    return False\n                req = """SELECT IDreponse, reponse\n                FROM questionnaire_reponses\n                WHERE IDquestion=%d AND IDindividu=%d;""" % (IDquestion, IDindividu)\n                DB.ExecuterReq(req)\n                listeReponses = DB.ResultatReq()     \n\n##                if dictQuestions[IDquestion]["type"] == "famille" :\n'''
if old not in source:
    raise SystemExit('badgeage questionnaire pattern not found')
source = source.replace(old, new, 1)
source_path.write_text(source, encoding='utf-8')

test_path = Path('tests/test_branch_contracts_batch_19.py')
test_path.write_text('''import importlib.util\nimport unittest\nfrom pathlib import Path\n\nROOT = Path(__file__).resolve().parents[1]\nNOETHYS = ROOT / "noethys"\nSOURCE_PATH = NOETHYS / "Dlg/DLG_Badgeage_interface.py"\nAUDIT = ROOT / "scripts" / "audit_branch_assignment_gaps.py"\nspec = importlib.util.spec_from_file_location("audit_branch_assignment_gaps", AUDIT)\naudit = importlib.util.module_from_spec(spec)\nspec.loader.exec_module(audit)\n\nTARGET = ("Dlg/DLG_Badgeage_interface.py", "VerificationConditionsAction", "listeReponses")\n\n\nclass TestBatch19BadgeageQuestionnaire(unittest.TestCase):\n    def test_targeted_finding_disappears(self):\n        remaining = [\n            (item["file"], item["function"], item["name"])\n            for item in audit.scan_file(SOURCE_PATH, NOETHYS)\n            if (item["file"], item["function"], item["name"]) == TARGET\n        ]\n        self.assertEqual(remaining, [])\n\n    def test_unsupported_or_missing_question_fails_closed_before_response_loop(self):\n        source = SOURCE_PATH.read_text(encoding="utf-8")\n        block = source[source.index("# Recherche les réponses", source.index("def VerificationConditionsAction")):source.index("# Compare le filtre", source.index("def VerificationConditionsAction"))]\n        self.assertIn('if IDquestion not in dictQuestions or dictQuestions[IDquestion]["type"] != "individu" :', block)\n        self.assertIn("DB.Close()", block)\n        self.assertIn("return False", block)\n        self.assertLess(block.index("return False"), block.index("listeReponses = DB.ResultatReq()"))\n\n    def test_supported_individual_question_keeps_historical_query(self):\n        source = SOURCE_PATH.read_text(encoding="utf-8")\n        self.assertIn("WHERE IDquestion=%d AND IDindividu=%d;", source)\n        self.assertIn("listeReponses = DB.ResultatReq()", source)\n\n\nif __name__ == "__main__":\n    unittest.main()\n''', encoding='utf-8')
