from pathlib import Path

piece = Path('noethys/Dlg/DLG_Saisie_piece.py')
text = piece.read_text(encoding='utf-8')
old = '''        if self.radio_pieces_1.GetValue() == True :\n            donnees = self.ctrl_pieces_obligatoires.GetDonneesSelection() \n            if donnees == None :\n                return None\n            if donnees["type"] == "famille" :\n                return\n            if donnees["type"] == "piece" :\n                IDtype_piece = donnees["IDtype_piece"]\n                IDindividu = donnees["IDindividu"]\n                IDfamille = donnees["IDfamille"]\n                nomPiece = donnees["nomPiece"]\n        elif self.radio_pieces_2.GetValue() == True:\n            donnees = self.ctrl_pieces_autres.GetDonneesSelection() \n            if donnees == None :\n                return None\n            IDtype_piece = donnees["IDtype_piece"]\n            IDindividu = donnees["IDindividu"]\n            IDfamille = donnees["IDfamille"]\n            nomPiece = donnees["nomPiece"]\n        elif self.radio_pieces_3.GetValue() == True:\n            IDfamille = self.IDfamille\n            IDtype_piece = None\n            IDindividu = None\n            nomPiece = None\n        return { "IDfamille":IDfamille, "IDtype_piece":IDtype_piece, "IDindividu":IDindividu, "nomPiece":nomPiece}\n'''
new = '''        if self.radio_pieces_1.GetValue() == True :\n            donnees = self.ctrl_pieces_obligatoires.GetDonneesSelection() \n            if donnees == None :\n                return None\n            if donnees["type"] == "famille" :\n                return None\n            if donnees["type"] != "piece" :\n                return None\n            IDtype_piece = donnees["IDtype_piece"]\n            IDindividu = donnees["IDindividu"]\n            IDfamille = donnees["IDfamille"]\n            nomPiece = donnees["nomPiece"]\n        elif self.radio_pieces_2.GetValue() == True:\n            donnees = self.ctrl_pieces_autres.GetDonneesSelection() \n            if donnees == None :\n                return None\n            IDtype_piece = donnees["IDtype_piece"]\n            IDindividu = donnees["IDindividu"]\n            IDfamille = donnees["IDfamille"]\n            nomPiece = donnees["nomPiece"]\n        elif self.radio_pieces_3.GetValue() == True:\n            IDfamille = self.IDfamille\n            IDtype_piece = None\n            IDindividu = None\n            nomPiece = None\n        else:\n            return None\n        return { "IDfamille":IDfamille, "IDtype_piece":IDtype_piece, "IDindividu":IDindividu, "nomPiece":nomPiece}\n'''
if old not in text:
    raise SystemExit('GetSelectionPiece block not found')
piece.write_text(text.replace(old, new), encoding='utf-8')

filters = Path('noethys/Dlg/DLG_Saisie_filtre_listes.py')
text = filters.read_text(encoding='utf-8')
old = '''    def GetValeur(self):\n        if self.check_cotisations.GetValue() == True:\n            choix = "AJOUR"\n            listeCotisations = self.ctrl_cotisations.GetTexteCoches()\n            date = self.ctrl_date.GetDate()\n            criteres = {"listeCotisations": listeCotisations, "date": str(date)}\n        return choix, criteres\n'''
new = '''    def GetValeur(self):\n        choix = None\n        criteres = None\n        if self.check_cotisations.GetValue() == True:\n            choix = "AJOUR"\n            listeCotisations = self.ctrl_cotisations.GetTexteCoches()\n            date = self.ctrl_date.GetDate()\n            criteres = {"listeCotisations": listeCotisations, "date": str(date)}\n        return choix, criteres\n'''
if old not in text:
    raise SystemExit('GetValeur block not found')
filters.write_text(text.replace(old, new), encoding='utf-8')

test = Path('tests/test_dialog_selection_branch_contracts.py')
test.write_text('''import ast\nimport pathlib\nimport unittest\n\nfrom scripts import audit_branch_assignment_gaps\n\nROOT = pathlib.Path(__file__).resolve().parents[1]\nSOURCE_ROOT = ROOT / "noethys"\nPIECE = SOURCE_ROOT / "Dlg" / "DLG_Saisie_piece.py"\nFILTERS = SOURCE_ROOT / "Dlg" / "DLG_Saisie_filtre_listes.py"\n\n\nclass DialogSelectionBranchContractsTests(unittest.TestCase):\n    def test_targeted_gaps_are_gone(self):\n        targeted = []\n        for source, function, names in ((PIECE, "GetSelectionPiece", {"IDfamille", "IDindividu", "IDtype_piece", "nomPiece"}), (FILTERS, "GetValeur", {"choix", "criteres"})):\n            targeted.extend(item for item in audit_branch_assignment_gaps.scan_file(source, SOURCE_ROOT) if item["function"] == function and item["name"] in names)\n        self.assertEqual(targeted, [], targeted)\n\n    def test_modules_parse(self):\n        ast.parse(PIECE.read_text(encoding="utf-8"), filename=str(PIECE))\n        ast.parse(FILTERS.read_text(encoding="utf-8"), filename=str(FILTERS))\n\n    def test_piece_selection_has_explicit_unselected_fallback(self):\n        text = PIECE.read_text(encoding="utf-8")\n        self.assertIn('        else:\\n            return None\\n        return { "IDfamille":IDfamille', text)\n        self.assertIn('            if donnees["type"] != "piece" :\\n                return None', text)\n\n    def test_disabled_filter_returns_neutral_pair(self):\n        text = FILTERS.read_text(encoding="utf-8")\n        self.assertIn('    def GetValeur(self):\\n        choix = None\\n        criteres = None', text)\n\n\nif __name__ == "__main__":\n    unittest.main()\n''', encoding='utf-8')
