#!/usr/bin/env python3
from pathlib import Path

repls = {
    Path('noethys/Dlg/DLG_Gestionnaire_conso.py'): [
        ('''        reponse = dlg.ShowModal()\n        if reponse == wx.ID_OK:\n            newLargeur = dlg.GetValue()\n            try:\n                newLargeur = int(newLargeur)\n            except Exception:\n                dlg2 = wx.MessageDialog(self, _(u"La valeur saisie semble incorrecte !"), _(u"Erreur de saisie"), wx.OK | wx.ICON_INFORMATION)\n                dlg2.ShowModal()\n                dlg2.Destroy()\n                dlg.Destroy()\n                return\n            if newLargeur < 30 or newLargeur > 300:\n                dlg2 = wx.MessageDialog(self, _(u"La valeur doit être comprise entre 30 et 300 !"), _(u"Erreur de saisie"), wx.OK | wx.ICON_INFORMATION)\n                dlg2.ShowModal()\n                dlg2.Destroy()\n                return\n            self.panel_grille.grille.SetLargeurColonneUnite(newLargeur)\n        dlg.Destroy()\n        UTILS_Config.SetParametre("largeur_colonne_unite", newLargeur)\n''', '''        reponse = dlg.ShowModal()\n        if reponse != wx.ID_OK:\n            dlg.Destroy()\n            return\n\n        newLargeur = dlg.GetValue()\n        try:\n            newLargeur = int(newLargeur)\n        except Exception:\n            dlg2 = wx.MessageDialog(self, _(u"La valeur saisie semble incorrecte !"), _(u"Erreur de saisie"), wx.OK | wx.ICON_INFORMATION)\n            dlg2.ShowModal()\n            dlg2.Destroy()\n            dlg.Destroy()\n            return\n        if newLargeur < 30 or newLargeur > 300:\n            dlg2 = wx.MessageDialog(self, _(u"La valeur doit être comprise entre 30 et 300 !"), _(u"Erreur de saisie"), wx.OK | wx.ICON_INFORMATION)\n            dlg2.ShowModal()\n            dlg2.Destroy()\n            dlg.Destroy()\n            return\n        self.panel_grille.grille.SetLargeurColonneUnite(newLargeur)\n        dlg.Destroy()\n        UTILS_Config.SetParametre("largeur_colonne_unite", newLargeur)\n''')
    ],
    Path('noethys/Dlg/DLG_Parametres_nbre_inscrits.py'): [
        ('''        if mode == "toutes" : \n            parametre = None\n        if mode == "groupes" : \n            parametre = "liste_groupes_activites###%s" % ";".join(listeID)\n        if mode == "activites" : \n            parametre = "liste_activites###%s" % ";".join(listeID)\n''', '''        if mode == "toutes" : \n            parametre = None\n        elif mode == "groupes" : \n            parametre = "liste_groupes_activites###%s" % ";".join(listeID)\n        elif mode == "activites" : \n            parametre = "liste_activites###%s" % ";".join(listeID)\n        else:\n            raise ValueError("Mode de sélection d'activités inconnu : %s" % mode)\n''')
    ],
    Path('noethys/Dlg/DLG_Saisie_contrat.py'): [
        ('''            if date_debut == None and date_fin == None : label = _(u"%s (Sans période de validité)") % nom\n            if date_debut == None and date_fin != None : label = _(u"%s (Jusqu'au %s)") % (nom, UTILS_Dates.DateDDEnFr(date_fin))\n            if date_debut != None and date_fin == None : label = _(u"%s (A partir du %s)") % (nom, UTILS_Dates.DateDDEnFr(date_debut))\n            if date_debut != None and date_fin != None : label = _(u"%s (Du %s au %s)") % (nom, UTILS_Dates.DateDDEnFr(date_debut), UTILS_Dates.DateDDEnFr(date_fin))\n''', '''            if date_debut == None and date_fin == None :\n                label = _(u"%s (Sans période de validité)") % nom\n            elif date_debut == None :\n                label = _(u"%s (Jusqu'au %s)") % (nom, UTILS_Dates.DateDDEnFr(date_fin))\n            elif date_fin == None :\n                label = _(u"%s (A partir du %s)") % (nom, UTILS_Dates.DateDDEnFr(date_debut))\n            else:\n                label = _(u"%s (Du %s au %s)") % (nom, UTILS_Dates.DateDDEnFr(date_debut), UTILS_Dates.DateDDEnFr(date_fin))\n''')
    ],
    Path('noethys/Ol/OL_Langues.py'): [
        ('''        dlg = Saisie(self)\n        code = None\n        if dlg.ShowModal() == wx.ID_OK:\n            code = dlg.GetCode()\n            nom = dlg.GetNom()\n        dlg.Destroy()\n        if code == None : \n            return\n''', '''        dlg = Saisie(self)\n        if dlg.ShowModal() != wx.ID_OK:\n            dlg.Destroy()\n            return\n        code = dlg.GetCode()\n        nom = dlg.GetNom()\n        dlg.Destroy()\n        if code == None : \n            return\n''')
    ],
    Path('noethys/Dlg/DLG_Individu_identite.py'): [
        ('''        else:\n            if IDcategorie == 1 and genre == "M" : IDcivilite = 1\n            if IDcategorie == 1 and genre == "F" : IDcivilite = 3\n            if IDcategorie == 2 and genre == "M" : IDcivilite = 4\n            if IDcategorie == 2 and genre == "F" : IDcivilite = 5\n            if IDcategorie == 3 and genre == "M" : IDcivilite = 1\n            if IDcategorie == 3 and genre == "F" : IDcivilite = 3\n            self.ctrl_civilite.SetID(IDcivilite)\n''', '''        else:\n            civilites = {\n                (1, "M"): 1, (1, "F"): 3,\n                (2, "M"): 4, (2, "F"): 5,\n                (3, "M"): 1, (3, "F"): 3,\n            }\n            try:\n                IDcivilite = civilites[(IDcategorie, genre)]\n            except KeyError:\n                raise ValueError("Catégorie ou genre inconnu : %s / %s" % (IDcategorie, genre))\n            self.ctrl_civilite.SetID(IDcivilite)\n''')
    ],
}

for path, replacements in repls.items():
    text = path.read_text(encoding='utf-8')
    for old, new in replacements:
        if old not in text:
            raise SystemExit(f'Pattern absent: {path}')
        text = text.replace(old, new, 1)
    path.write_text(text, encoding='utf-8')

Path('tests/test_small_ui_branch_contracts_batch_12.py').write_text('''\nimport unittest\nfrom pathlib import Path\nfrom scripts import audit_branch_assignment_gaps\n\nROOT = Path(__file__).resolve().parents[1]\nSRC = ROOT / "noethys"\n\nTARGETS = {\n    ("Dlg/DLG_Gestionnaire_conso.py", "On_affichage_largeur_unite", "newLargeur"),\n    ("Dlg/DLG_Parametres_nbre_inscrits.py", "OnBoutonOk", "parametre"),\n    ("Dlg/DLG_Saisie_contrat.py", "MAJ", "label"),\n    ("Ol/OL_Langues.py", "Ajouter", "nom"),\n    ("Dlg/DLG_Individu_identite.py", "SetValeursDefaut", "IDcivilite"),\n}\n\nclass TestBatch12Contracts(unittest.TestCase):\n    def test_targeted_findings_disappear(self):\n        remaining = set()\n        for rel, func, name in TARGETS:\n            findings = audit_branch_assignment_gaps.scan_file(SRC / rel, SRC)\n            for item in findings:\n                key = (item["file"], item["function"], item["name"])\n                if key in TARGETS:\n                    remaining.add(key)\n        self.assertEqual(remaining, set(), remaining)\n\n    def test_cancelled_width_dialog_returns_before_persist(self):\n        text = (SRC / "Dlg/DLG_Gestionnaire_conso.py").read_text(encoding="utf-8")\n        self.assertIn("if reponse != wx.ID_OK:", text)\n        self.assertIn("UTILS_Config.SetParametre(\\\"largeur_colonne_unite\\\", newLargeur)", text)\n\n    def test_contract_mode_is_exhaustive(self):\n        text = (SRC / "Dlg/DLG_Parametres_nbre_inscrits.py").read_text(encoding="utf-8")\n        self.assertIn("raise ValueError(\\\"Mode de sélection d'activités inconnu", text)\n\nif __name__ == "__main__":\n    unittest.main()\n''', encoding='utf-8')
