from pathlib import Path
p=Path('noethys/Dlg/DLG_Individu.py')
s=p.read_text(encoding='utf-8')
old='''                # Efface de la base la fiche individu \n                DB = GestionDB.DB()\n                DB.ReqDEL("individus", "IDindividu", self.IDindividu)\n                DB.ReqDEL("rattachements", "IDindividu", self.IDindividu)\n                DB.ReqDEL("liens", "IDindividu_sujet", self.IDindividu)\n                DB.ReqDEL("liens", "IDindividu_objet", self.IDindividu)\n                DB.ReqDEL("vaccins", "IDindividu", self.IDindividu)\n                DB.ReqDEL("problemes_sante", "IDindividu", self.IDindividu)\n                DB.ReqDEL("questionnaire_reponses", "IDindividu", self.IDindividu)\n                DB.ReqDEL("messages", "IDindividu", self.IDindividu)\n                DB.ReqDEL("scolarite", "IDindividu", self.IDindividu)\n                DB.ReqDEL("transports", "IDindividu", self.IDindividu)\n                DB.Close() \n                # Suppression de la photo \n                DB = GestionDB.DB(suffixe="PHOTOS")\n                DB.ReqDEL("photos", "IDindividu", self.IDindividu)\n                DB.Close()\n                dlg.Destroy()\n                # Ferme la fenêtre\n                self.Destroy()\n'''
new='''                # Efface de la base la fiche individu et ses dépendances\n                DB = GestionDB.DB()\n                suppressions = [\n                    ("rattachements", "IDindividu"),\n                    ("liens", "IDindividu_sujet"),\n                    ("liens", "IDindividu_objet"),\n                    ("vaccins", "IDindividu"),\n                    ("problemes_sante", "IDindividu"),\n                    ("questionnaire_reponses", "IDindividu"),\n                    ("messages", "IDindividu"),\n                    ("scolarite", "IDindividu"),\n                    ("transports", "IDindividu"),\n                    ("individus", "IDindividu"),\n                ]\n                suppression_ok = True\n                for table, champ in suppressions:\n                    if not DB.ReqDEL(table, champ, self.IDindividu, commit=False):\n                        suppression_ok = False\n                        break\n                if not suppression_ok:\n                    try:\n                        DB.connexion.rollback()\n                    except Exception:\n                        pass\n                    DB.Close()\n                    dlg.Destroy()\n                    dlg_erreur = wx.MessageDialog(self, _(u"La suppression de la nouvelle fiche a échoué. Aucune donnée principale n'a été supprimée."), _(u"Erreur"), wx.OK | wx.ICON_ERROR)\n                    dlg_erreur.ShowModal()\n                    dlg_erreur.Destroy()\n                    return False\n                DB.Commit()\n                DB.Close()\n\n                # Suppression de la photo dans la base PHOTOS distincte\n                DBphotos = GestionDB.DB(suffixe="PHOTOS")\n                photo_ok = DBphotos.ReqDEL("photos", "IDindividu", self.IDindividu)\n                DBphotos.Close()\n                if not photo_ok:\n                    dlg_photo = wx.MessageDialog(self, _(u"La fiche a été supprimée, mais la suppression de sa photo a échoué."), _(u"Avertissement"), wx.OK | wx.ICON_WARNING)\n                    dlg_photo.ShowModal()\n                    dlg_photo.Destroy()\n                dlg.Destroy()\n                # Ferme la fenêtre\n                self.Destroy()\n'''
if old not in s:
    raise SystemExit('bloc annulation individu introuvable')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
