from pathlib import Path
p=Path('noethys/Dlg/DLG_Saisie_contratpsu.py')
s=p.read_text(encoding='utf-8')
old='''        if self.IDcontrat == None :\n            self.IDcontrat = DB.ReqInsert("contrats", listeDonnees)\n        else :\n            DB.ReqMAJ("contrats", listeDonnees, "IDcontrat", self.IDcontrat)\n'''
new='''        ancien_IDcontrat = self.IDcontrat\n        if ancien_IDcontrat == None :\n            IDcontrat = DB.ReqInsert("contrats", listeDonnees, commit=False)\n            if IDcontrat is None:\n                DB.Close()\n                return False\n        else :\n            IDcontrat = ancien_IDcontrat\n            if not DB.ReqMAJ("contrats", listeDonnees, "IDcontrat", IDcontrat, commit=False):\n                DB.Close()\n                return False\n'''
if old not in s: raise SystemExit('bloc contrat introuvable')
s=s.replace(old,new,1)
s=s.replace('DB.Executermany("INSERT INTO consommations (%s) VALUES (%s)" % (texteChampsTemp, texteInterrogations), listeAjouts, commit=True)', 'DB.Executermany("INSERT INTO consommations (%s) VALUES (%s)" % (texteChampsTemp, texteInterrogations), listeAjouts, commit=False)',1)
s=s.replace('DB.Executermany("UPDATE consommations SET %s WHERE IDconso=?" % ", ".join(listeChampsTemp), listeModifications, commit=True)', 'DB.Executermany("UPDATE consommations SET %s WHERE IDconso=?" % ", ".join(listeChampsTemp), listeModifications, commit=False)',1)
s=s.replace('''            DB.Executermany("INSERT INTO consommations (%s) VALUES (%s)" % (texteChampsTemp, texteInterrogations), listeAjouts, commit=False)\n''','''            if not DB.Executermany("INSERT INTO consommations (%s) VALUES (%s)" % (texteChampsTemp, texteInterrogations), listeAjouts, commit=False):\n                DB.Close()\n                return False\n''',1)
s=s.replace('''            DB.Executermany("UPDATE consommations SET %s WHERE IDconso=?" % ", ".join(listeChampsTemp), listeModifications, commit=False)\n''','''            if not DB.Executermany("UPDATE consommations SET %s WHERE IDconso=?" % ", ".join(listeChampsTemp), listeModifications, commit=False):\n                DB.Close()\n                return False\n''',1)
s=s.replace('''            DB.ExecuterReq("DELETE FROM consommations WHERE IDconso IN %s" % conditionSuppression)\n''','''            if not DB.ExecuterReq("DELETE FROM consommations WHERE IDconso IN %s" % conditionSuppression):\n                try:\n                    DB.connexion.rollback()\n                except Exception:\n                    pass\n                DB.Close()\n                return False\n''',1)
s=s.replace('(\"IDcontrat\", self.IDcontrat),','(\"IDcontrat\", IDcontrat),',1)
s=s.replace('''                IDcontrat_tarif = DB.ReqInsert("contrats_tarifs", listeDonnees)\n''','''                IDcontrat_tarif = DB.ReqInsert("contrats_tarifs", listeDonnees, commit=False)\n                if IDcontrat_tarif is None:\n                    DB.Close()\n                    return False\n''',1)
s=s.replace('''                DB.ReqMAJ("contrats_tarifs", listeDonnees, "IDcontrat_tarif", IDcontrat_tarif)\n''','''                if not DB.ReqMAJ("contrats_tarifs", listeDonnees, "IDcontrat_tarif", IDcontrat_tarif, commit=False):\n                    DB.Close()\n                    return False\n''',1)
s=s.replace('''            DB.ExecuterReq("DELETE FROM contrats_tarifs WHERE IDcontrat_tarif IN %s" % conditionSuppression)\n''','''            if not DB.ExecuterReq("DELETE FROM contrats_tarifs WHERE IDcontrat_tarif IN %s" % conditionSuppression):\n                try:\n                    DB.connexion.rollback()\n                except Exception:\n                    pass\n                DB.Close()\n                return False\n''',1)
s=s.replace('''        DB.Commit()\n        DB.Close()\n\n\n    def Importation''','''        DB.Commit()\n        DB.Close()\n        self.IDcontrat = IDcontrat\n        return True\n\n\n    def Importation''',1)
p.write_text(s,encoding='utf-8')
